apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - security.eval.io_v1alpha1_opencodeagent_sast.yaml
  - security.eval.io_v1alpha1_opencodeagent_fuzz.yaml
  - security.eval.io_v1alpha1_opencodeagent_rogue.yaml
  - security.eval.io_v1alpha1_opencodeagent_synth.yaml
  - security.eval.io_v1alpha1_mcpserver.yaml
